pull_request_title: "docs(i18n): New Crowdin translations"
files:
  - source: /docs/**/*.md
    translation: /docs/**/%file_name%.%two_letters_code%.%file_extension%
    ignore:
      - /docs/**/%file_name%.%two_letters_code%.%file_extension%
